server:
  port: 0  # 랜덤 포트
#  port: 8081
spring:
  application:
    name: jw-first-api-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # eureka 에서 service 명 구분하기 위하여 추가 (port 가 0 일경우 모든 service 가 0 으로 뜸)
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}